/*
 https://ywait.in:2003 --> Staging
 https://y-wait.com:2001 --> QA
 https://y-wait.com:5002 --> Development
 https://ywait.org:8881 --> Prod
*/
export default {
  BASE_URL: 'https://ywait.org:8881', //'https://y-wait.com:2001',
  URL_TYPE: 'Prod', //Dev, QA, Staging, Prod, Custom
  DEV_URL: 'https://y-wait.com:5002',
  QA_URL: 'https://y-wait.com:2001',
  STAGE_URL: 'https://ywait.in:2003',
  PROD_URL: 'https://ywait.org:8881',
  DEFAULT_URL: 'https://ywait.org:8881', // 'https://y-wait.com:2001',

  ENDPOINTS: {
    EMAIL_LOGIN: '/app/v0.1/customer/email/login',
    PHONE_LOGIN: '/app/v0.1/customer/signup',
    GOOGLE_SIGN_IN: '/app/v0.1/customer/emailsignup',
    FACEBOOK_SIGN_IN: '/app/v0.1/customer/facebooksignup',
    APPLE_SIGN_IN: '/app/v0.1/customer/applesignup',
    BUSINESS_LIST: '/app/v0.1/customer/list/business',
    BUSINESS_DETAILS: '/app/v0.1/customer/business-detail',
    OTP_VALIDATION: '/app/v0.1/customer/verify/otp',
    RESEND_OTP: '/app/v0.1/customer/resend/otp',
    EMAIL_REGISTER: '/app/v0.1/customer/email/register',
    COUNTRY_CODE: '/app/v0.1/customer/list/countryCode',
    STATE_AND_CITY: '/app/v0.1/customer/list-countries',
    PROFILE_UPDATE: '/app/v0.1/customer/profile/update',
    UPDATE_PASSWORD: '/app/v0.1/customer/update/password',
    USER_DETAILS: '/app/v0.1/customer/detail',
    PASSWORD_CHANGE: '/app/v0.1/customer/change/password',
    EMAIL_UPDATE: '/app/v0.1/customer/reset/email',
    FORGOT_PASSWORD: '/app/v0.1/customer/forgot/password',
    SPECIALIST_LIST: '/app/v0.1/customer/list-serving-user', //Price issue in app api, using web to test(/web/customer/list-serving-user)
    NOTIFICATION_LIST: '/app/v0.1/customer/notification',
    UPDATE_NOTIFICATION: '/app/v0.1/customer/update/read-status',
    UPDATE_NOTIFICATION_ALL: '/app/v0.1/customer/update-all/read-status',
    DEVICE_REGISTRATION: '/app/v0.1/customer/register/device',
    UPCOMING_LIST: '/app/v0.1/customer/list/bookings',
    SERVICES_LIST: '/app/v0.1/customer/services',
    MESSAGES: '/app/v0.1/customer/appointment/messages',
    BOOKING_APPOINTMENT_DETAILS: '/app/v0.1/customer/booking/detail/',
    QUEUE_APPOINTMENT_DETAILS: '/app/v0.1/customer/queue-detail/',
    DEPARTMENT_LIST: '/app/v0.1/customer/department/list',
    FAVOURITE_LIST: '/app/v0.1/customer/favourite-user-list',
    CANCEL_BOOKING: '/app/v0.1/customer/update/booking-status',
    CANCEL_QUEUE: '/app/v0.1/customer/waitlist/update',
    PROFILE_IMAGE_UPLOAD: '/app/v0.1/customer/profile/image',
    AVAILABLE_BOOKING: '/app/v0.1/customer/booking/available',
    BOOKING_ALL_SLOT: '/app/v0.1/customer/slots/list',
    AVAILABLE_QUEUE: '/app/v0.1/customer/queue-slots',
    QUEUE_ALL_SLOT: '/app/v0.1/customer/queue/slots/list',
    ADD_REVIEW: '/app/v0.1/customer/writereview',
    BOOKING_PAYMENT_INIT: '/app/v0.1/customer/payment/appointment',
    QUEUE_PAYMENT_INIT: '/app/v0.1/customer/payment/queue',
    ADD_BOOKING: '/app/v0.1/customer/new/booking',
    ADD_QUEUE: '/app/v0.1/customer/add/waitlist',
    RESCHEDULE_BOOKING: '/app/v0.1/customer/update/booking',
    DASHBOARD_COUNTS: '/app/v0.1/customer/booking/dashboard',
    STORY_LIST: '/app/v0.1/customer/story/list',
    REPORT_LATE_BOOKING: '/app/v0.1/customer/request/booking/delay',
    REPORT_LATE_QUEUE: '/app/v0.1/customer/request/queue/delay',
    MARK_ATTENDANCE: '/app/v0.1/customer/update/attendance',
    TODAYS_APPOINTMENTS: '/app/v0.1/customer/scan-qr',
    UPDATE_BOOKING_VIEW_STATUS: '/app/v0.1/customer/update/booking-view-status',
    UPDATE_QUEUE_VIEW_STATUS: '/app/v0.1/customer/update/waitlist-view-status',
    LOGOUT: '/app/v0.1/customer/logout',
  },

  KEYS: {
    BUSINESS_ID: 'business_id',
    USERNAME: 'userName',
    PASSWORD: 'password',
    EMAIL_ID: 'emailId',
    FACEBOOK_ID: 'faceBookId',
    APPLE_ID: 'appleId',
    ADMIN_ID: 'admin_id',
    USER_ID: 'user_id',
    SERVING_USER_ID: 'servingUser_id',
    AUTHORIZATION: 'Authorization',
    PHONE_NUMBER: 'phoneNumber',
    AUTHENTICATION_PIN: 'authenticationPin',
    STATUS: 'status',
    EMAIL: 'email',
    COUNTRY_CODE: 'countryCode',
    TIME: 'time',
    OTP: 'otp',
    START_DATE: 'startDate',
    END_DATE: 'endDate',
    BOOKING_ID: 'booking_id',
    QUEUE_ID: 'queue_id',
    WAITLIST_ID: 'waitlist_id',
    CUSTOMER_ID: 'customer_id',
    LATITUDE: 'latitude',
    LONGITUDE: 'longitude',
    DURATION: 'duration',
    PAYMENT_TYPE: 'paymentType',
    PAYMENT_ID: 'paymentId',
    PAYMENT_STATUS: 'paymentStatus',
    SERVICES: 'services',
    SERVICE_IDS: 'serviceIds',
    EXPECTED_TIME_OF_SERVING: 'expectedTimeOfServing',
    PREFERRED_TIME_FROM: 'preferedTimeFrom',
    PREFERRED_TIME_TO: 'preferedTimeTo',
    GENDER: 'gender',
    READ_STATUS: 'readStatus',
    NOTIFICATION_ID: 'notification_id',
    CONSULTATION_ID: 'consultation_id',
    NOTES: 'notes',
    IMAGE: 'image',
    NOTES_IMAGES: 'notesImages',
    NEXT_SCHEDULE_DATE: 'nextScheduleDate',
    FILTER: 'filter',
    DEVICE_ID: 'device_id',
    DEVICE: 'device',
    TOKEN: 'device_token_id',
    OLD_PASSWORD: 'oldPassword',
    NEW_PASSWORD: 'newPassword',
    CONSULTATION_DATE: 'consultationDate',
    NOTE_ID: 'note_id',
    SEARCH: 'search',
    COMMENT: 'comment',
    RATING: 'rating',
    AUTHOR_ID: 'author_id',
    IS_RESCHEDULE: 'isReschedule',
    CANCEL_BOOKING: 'cancellBooking',
    CANCEL_QUEUE: 'cancellQueue',
    DELAY: 'delay',
  },
};
